name: OWASP ZAP Dynamic Scan

on:
  push:
    branches:
      - master

jobs:
  zap_scan:
    name: OWASP ZAP Security Scan
    runs-on: ubuntu-latest

    steps:
      - name: Start ZAP Scan
        uses: zaproxy/action-full-scan@v0.10.0
        with:
          target: 'https://asiaone.com'
          rules_file_name: '.zap/rules.tsv'
          cmd_options: '-a'

